# Generated by Django 2.0.3 on 2018-06-17 17:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworldentity',
            name='array_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=8),
        ),
        migrations.AlterField(
            model_name='helloworldentity',
            name='integer_range_field',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='helloworldentity',
            name='json_field',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
